<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SVJain-PC" ignored="0" name="Default test" tests="3" failures="1" timestamp="20 Aug 2017 21:57:26 GMT" time="27.709" errors="0">
  <testcase name="task1" time="18.914" classname="dataliciousAssignment.NewPhantomJsTest">
    <failure type="java.lang.AssertionError" message="Incorrect URL opened! expected [https://www.datalicious.com/] but found [http://www.google.co.in/search?hl=en-IN&amp;amp;source=hp&amp;amp;biw=&amp;amp;bih=&amp;amp;q=Datalicious&amp;amp;gbv=2&amp;amp;oq=Datalicious&amp;amp;gs_l=heirloom-hp.12..0l10.2338.2360.0.4433.11.2.0.0.0.0.173.282.0j2.2.0....0...1.1.34.heirloom-hp..9.2.282.Xw5jxUx_R68]">
      <![CDATA[java.lang.AssertionError: Incorrect URL opened! expected [https://www.datalicious.com/] but found [http://www.google.co.in/search?hl=en-IN&source=hp&biw=&bih=&q=Datalicious&gbv=2&oq=Datalicious&gs_l=heirloom-hp.12..0l10.2338.2360.0.4433.11.2.0.0.0.0.173.282.0j2.2.0....0...1.1.34.heirloom-hp..9.2.282.Xw5jxUx_R68]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at dataliciousAssignment.NewPhantomJsTest.task1(NewPhantomJsTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- task1 -->
  <testcase name="task2" time="0.0" classname="dataliciousAssignment.NewPhantomJsTest">
    <skipped/>
  </testcase> <!-- task2 -->
  <testcase name="task3" time="0.0" classname="dataliciousAssignment.NewPhantomJsTest">
    <skipped/>
  </testcase> <!-- task3 -->
</testsuite> <!-- Default test -->
